import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const exportToPDF = async (result: any, ideaText: string) => {
  try {
    // Create a temporary div with the content to be exported
    const exportContent = document.createElement('div');
    exportContent.style.cssText = `
      width: 800px;
      padding: 40px;
      font-family: 'Arial', sans-serif;
      background: white;
      color: black;
      position: fixed;
      top: -10000px;
      left: -10000px;
    `;

    exportContent.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #6366f1; margin: 0; font-size: 28px;">🚀 Startup Idea Analysis</h1>
        <p style="color: #64748b; margin: 10px 0; font-size: 14px;">Generated on ${new Date().toLocaleDateString()}</p>
      </div>
      
      <div style="margin-bottom: 25px;">
        <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">💡 Original Idea</h2>
        <p style="background: #f8fafc; padding: 15px; border-left: 4px solid #6366f1; margin: 0; line-height: 1.6; font-size: 14px;">${ideaText}</p>
      </div>

      <div style="display: flex; justify-content: space-between; margin-bottom: 25px;">
        <div style="width: 48%;">
          <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">📊 Feasibility Score</h2>
          <div style="text-align: center; background: #f8fafc; padding: 20px; border-radius: 8px;">
            <div style="font-size: 36px; font-weight: bold; color: ${result.feasibilityScore >= 80 ? '#10b981' : result.feasibilityScore >= 60 ? '#f59e0b' : '#ef4444'}; margin-bottom: 5px;">${result.feasibilityScore}</div>
            <div style="font-size: 14px; color: #64748b;">${result.feasibilityScore >= 80 ? 'High' : result.feasibilityScore >= 60 ? 'Moderate' : 'Low'} Feasibility</div>
          </div>
        </div>
        
        <div style="width: 48%;">
          <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">🎯 Target Audience</h2>
          <div style="background: #f8fafc; padding: 15px; border-radius: 8px; height: 100px; display: flex; align-items: center;">
            <p style="margin: 0; font-size: 14px; line-height: 1.5;">${result.targetAudience}</p>
          </div>
        </div>
      </div>

      <div style="margin-bottom: 25px;">
        <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">🏢 Competitors</h2>
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
          ${result.competitors.map((competitor: string) => `
            <div style="display: inline-block; background: white; padding: 8px 12px; margin: 4px; border-radius: 20px; border: 1px solid #e2e8f0; font-size: 14px;">${competitor}</div>
          `).join('')}
        </div>
      </div>

      <div style="margin-bottom: 25px;">
        <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">💰 Monetization Strategies</h2>
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
          ${result.monetizationStrategies.map((strategy: string, index: number) => `
            <div style="margin: 8px 0; padding: 10px; background: white; border-radius: 6px; border-left: 4px solid #10b981; font-size: 14px;">
              <strong>${index + 1}.</strong> ${strategy}
            </div>
          `).join('')}
        </div>
      </div>

      <div style="margin-bottom: 25px;">
        <h2 style="color: #1e293b; font-size: 18px; margin-bottom: 10px;">⚡ Suggested Tech Stack</h2>
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
          ${result.suggestedTechStack.map((tech: string) => `
            <div style="display: inline-block; background: #6366f1; color: white; padding: 8px 12px; margin: 4px; border-radius: 20px; font-size: 14px;">${tech}</div>
          `).join('')}
        </div>
      </div>

      <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
        <p style="color: #64748b; font-size: 12px; margin: 0;">Generated by Startup Idea Validator</p>
      </div>
    `;

    document.body.appendChild(exportContent);

    // Convert to canvas
    const canvas = await html2canvas(exportContent, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
      allowTaint: true,
    });

    // Remove the temporary element
    document.body.removeChild(exportContent);

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    
    const imgWidth = 210;
    const pageHeight = 295;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Save the PDF
    const fileName = `startup-analysis-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);

    return true;
  } catch (error) {
    console.error('Error exporting PDF:', error);
    throw new Error('Failed to export PDF');
  }
};
